export const meta = {
  name: 'voltic-hd-upgrade',
  description: 'Build detailed can, post-processing and page-detail modules for the VOLTIC site',
  phases: [
    { title: 'Build', detail: 'label artwork, can geometry, post-processing, addon API, page sections' },
    { title: 'Verify', detail: 'runtime-check each module loads and exports its contract' },
  ],
}

const ROOT = 'c:/Users/Fahad Bhutta/Desktop/figma'

const REF_LINES = [
  'DESIGN REFERENCE - read these images, they ARE the target look:',
  '  - ' + ROOT + '/_ref/crop-hero.png    (hero: giant brand wordmark with the can composited into it)',
  '  - ' + ROOT + '/_ref/crop-can.png     (the can, close up)',
  '  - ' + ROOT + '/_ref/crop-since.png   (split section: greyscale media panel + huge italic statement)',
  '  - ' + ROOT + '/_ref/crop-flavors.png (product row of cans)',
  '  - ' + ROOT + '/_ref/thumb-1080.png   (all three frames together)',
]

const STYLE_LINES = [
  'The reference design language, in short:',
  '  * The can body is MATTE NEAR-BLACK, not a coloured gradient. Later it carries ONE',
  '    large accent-coloured angular shard logo (built from 4-6 pointed blade polygons',
  '    with white highlight edges), a VERTICAL (rotated 90 degrees) heavy wordmark in',
  '    white-to-accent, tiny vertical monospace spec columns, and small white',
  '    micro-text. Very high contrast, very little ink on the can.',
  '  * One accent colour only, acid lime; everything else greyscale.',
  '  * Tiny monospace UI labels everywhere; enormous condensed display type.',
]

const RULES_LINES = [
  'HARD RULES',
  '  * No new network dependencies. No image or 3D asset files. Everything procedural.',
  '  * three is loaded via an importmap: bare "three" and "three/addons/" both resolve.',
  '    Version is pinned to 0.169.0 - do not use APIs newer than that.',
  '  * No build step. Plain ES modules that run in the browser as-is.',
  '  * Match the surrounding code comment style: explain WHY, not what. Full',
  '    sentences. Do not over-comment obvious lines.',
  '  * Write ONLY the file you are asked for. Do not edit any other file.',
]

const BRIEF = [
  'PROJECT: ' + ROOT + ' - a scroll-driven 3D energy-drink landing page.',
  'Read these first, they are the ground truth for conventions and the design:',
  '  - ' + ROOT + '/js/scene.js   (the existing Three.js layer you are extending)',
  '  - ' + ROOT + '/js/app.js     (orchestration; never touches WebGL)',
  '  - ' + ROOT + '/index.html',
  '  - ' + ROOT + '/css/style.css',
  '',
].concat(REF_LINES, [''], STYLE_LINES, [''], RULES_LINES).join('\n')

const SCHEMA = {
  type: 'object',
  required: ['file', 'summary', 'verifyCommand', 'verifyResult', 'risks'],
  properties: {
    file: { type: 'string', description: 'path of the file you created' },
    summary: { type: 'string', description: 'what it does and the exact exported API' },
    verifyCommand: { type: 'string', description: 'the command you ran to check it' },
    verifyResult: { type: 'string', description: 'what the check actually printed' },
    risks: { type: 'string', description: 'integration risks or things that could break' },
    todosForIntegrator: { type: 'string', description: 'anything the integrator must do' },
  },
}

const LABEL_TASK = [
  'YOUR TASK: write ' + ROOT + '/js/can-label.js - the can printed artwork generator.',
  '',
  'CONTRACT (must match exactly, the integrator depends on it):',
  '  export const LABEL_SERVICE = 2048;             // canvas edge in px',
  '  export const BAND = { y0: 0.169, y1: 0.892 };  // printed band, fractions of canvas height',
  '  export function makeLabelTexture(flavor, service = LABEL_SERVICE) -> THREE.CanvasTexture',
  '  flavor is an object { key, name, accent, base, deep, ink } - see FLAVORS in scene.js.',
  '',
  'The canvas is mapped around the can by a LatheGeometry: u wraps the full 2*pi',
  'circumference, and u = 0.5 is the point that faces the camera at rest (the lathe',
  'uses phiStart = PI). Draw the artwork THREE times, centred at canvas x = 0, 0.5*S',
  'and S, so it reads from the front, the back, and the wrap point without a cut.',
  '',
  'CRITICAL - readable arc: only about the front 28% of the canvas width is legible',
  'once wrapped; past roughly plus or minus 50 degrees the surface foreshortens so',
  'hard that letters collapse into the silhouette. Call it FRONT = S * 0.28 and',
  'auto-fit every string inside it (measure with ctx.measureText and shrink until it',
  'fits). At 2048 that is about 573px, so you have a LOT more room than the current',
  '1024 version - use it for real detail, not bigger type.',
  '',
  'WHAT TO DRAW (this is the whole point of the task - be dense and specific):',
  '  1. Matte near-black base across the whole canvas (about #0a0a0b), NOT a coloured',
  '     gradient band. A very subtle vertical lightening so it reads as a lit cylinder.',
  '  2. A large angular SHARD LOGO centred on each seam: a stylised bolt or N built from',
  '     4-6 pointed blade polygons, filled with an accent -> white -> accent linear',
  '     gradient so it reads as polished metal catching light, with white hairline',
  '     edges. Look at crop-can.png and match that construction.',
  '  3. A VERTICAL wordmark: the brand name rotated -90 degrees, heavy condensed face',
  '     (Anton, Arial Narrow, sans-serif), filled with a white -> accent vertical',
  '     gradient. In the reference this sits to the left of the shard logo.',
  '  4. Tiny vertical monospace columns beside the wordmark (like ENERGY DRINK and',
  '     200MG CAFFEINE) using JetBrains Mono, monospace.',
  '  5. A real micro-detail layer, all drawn procedurally:',
  '     - an EAN-13 style barcode with correct-looking guard bars and varying widths',
  '     - a recycling triangle outline with the material code',
  '     - a small nutrition panel: a boxed grid with a few rows and hairline rules',
  '     - a batch or lot code, and a made-up best-before style date stamp',
  '     - 500 ML and the caffeine line',
  '     - the manufacturer block in genuinely tiny type',
  '     - a few registration or crop marks and hairlines, as if the can were printed',
  '  6. A faint noise, scratch and brushed-grain overlay across the band so it is not a',
  '     flat vector fill. Use a deterministic seeded LCG, NOT Math.random, so the',
  '     texture is stable across reloads.',
  '  7. Rules top and bottom of the printed band in the accent colour.',
  '',
  'Also export:',
  '  export function refreshLabels(flavors, service) -> THREE.CanvasTexture[]',
  '',
  'VERIFY IT YOURSELF before returning. There is no Pillow and no ImageMagick, but',
  'this project has ' + ROOT + '/_crop.mjs which renders an image region through',
  'headless Chrome over CDP - read it and adapt the technique. Write a throwaway',
  'harness under ' + ROOT + '/_tmp/ that opens a page importing your module from the',
  'real unpkg three URL, calls makeLabelTexture for each flavour, draws the returned',
  'canvas into the page, and screenshots it to a PNG. Then READ that PNG and look at',
  'it. Iterate until the artwork genuinely looks like the reference: black can, one',
  'bold shard logo, legible vertical wordmark, dense believable micro-text. Delete',
  'your throwaway files when done. Report honestly what you saw.',
].join('\n')

const MESH_TASK = [
  'YOUR TASK: write ' + ROOT + '/js/can-mesh.js - the can geometry builders.',
  '',
  'CONTRACT (must match exactly, the integrator depends on it):',
  '  export const CAN = { bodyR, bodyTop, bodyBot, neckR, neckTop, baseBot,',
  '                       domeSteps, bodySteps, neckSteps, bandVBot, bandVTop,',
  '                       radialSegments };',
  '  export function buildBodyGeometry(radialSegments = CAN.radialSegments) -> THREE.LatheGeometry',
  '  export function buildLid()  -> THREE.BufferGeometry',
  '  export function buildTab()  -> THREE.BufferGeometry',
  '  export function buildRim()  -> THREE.BufferGeometry',
  '  export function buildFoot() -> THREE.BufferGeometry',
  '  export function buildUnderBase() -> THREE.BufferGeometry',
  '',
  'THE UV CONTRACT IS LOAD-BEARING - DO NOT CHANGE IT:',
  '  LatheGeometry assigns the texture v coordinate by point INDEX, not arc length.',
  '  The current profile has exactly 84 points (indices 0..83, divisor 83):',
  '    DOME_STEPS = 10  -> indices 0..9   (bottom dome, centre to shoulder)',
  '    BODY_STEPS = 60  -> indices 9..69  (straight body; index 69 is the TOP of the body)',
  '    NECK_STEPS = 14  -> indices 70..83 (neck taper up to the rim)',
  '  So bandVBot = 9/83 and bandVTop = 69/83, and the label canvas BAND y0/y1 are',
  '  derived from those (y0 = 1 - bandVTop, y1 = 1 - bandVBot). Keep the point COUNT',
  '  and this index layout exactly. Get it wrong and the label artwork lands in the',
  '  wrong place on the can - this has already bitten once.',
  '',
  'WHAT TO IMPROVE (the whole point of the task):',
  '  * The current body is a bare lathe with a flat circular lid and a torus tab.',
  '    Make it read like a real aluminium can at large on-screen size:',
  '    - a proper rolled TOP RIM (a small swept or torus profile at the rim edge, so',
  '      the neck does not just stop dead)',
  '    - a RECESSED LID: an inset disc, a raised outer ring, and a SCORED OPENING',
  '      line around the drink hole',
  '    - a real STAY-ON TAB: a flat plate with a finger hole and a rivet, lying in',
  '      the lid recess - build it from extruded shapes, not one torus',
  '    - a FOOT RING at the base and the characteristic CONCAVE UNDER-BASE dome',
  '      (real cans curve inward underneath)',
  '    - give the straight body a very slight barrel or taper, a few tenths of a',
  '      percent, rather than a mathematically perfect cylinder',
  '  * Radius and height should stay in the same proportion as now (about 2 units',
  '    wide, 4.94 tall) so the existing camera framing and PRESETS still work.',
  '',
  'Use THREE.LatheGeometry, THREE.ExtrudeGeometry, THREE.Shape and THREE.TorusGeometry',
  'as appropriate. Return raw geometries only - the integrator creates the materials.',
  '',
  'VERIFY IT YOURSELF: write a throwaway node script under ' + ROOT + '/_tmp/ that',
  'imports your module with three resolved from the real unpkg module URL, and',
  'asserts: the profile has exactly 84 points, the divisor is 83, y is monotonically',
  'increasing, index 69 is still at bodyTop, and bandVBot/bandVTop are 9/83 and 69/83.',
  'Print the numbers. Delete the throwaway when done. Report the actual printed numbers.',
].join('\n')

const POSTFX_TASK = [
  'YOUR TASK: write ' + ROOT + '/js/postfx.js - a post-processing stack, self-contained.',
  '',
  'The site currently renders with a bare renderer.render(). It looks flat and soft.',
  'The goal is a crisp, cinematic, super HD image. Read js/scene.js to see how the',
  'renderer, scene and camera are created.',
  '',
  'CONTRACT (must match exactly, the integrator depends on it):',
  '  export function createPostFX(renderer, scene, camera, opts = {}) returns an object with:',
  '    render(dt)            // renders the composer instead of the raw renderer',
  '    setSize(width, height)',
  '    setAccent(hexColor)   // so bloom can be tinted per flavour',
  '    setEnabled(bool)',
  '    dispose()',
  '    composer              // exposed for debugging',
  '',
  'WHAT IT SHOULD DO:',
  '  * EffectComposer + RenderPass + UnrealBloomPass + a custom ShaderPass + OutputPass.',
  '    Import them from three/addons/postprocessing/... - verify the EXACT paths and',
  '    constructor signatures against three 0.169.0 before you write them. Do not trust',
  '    your memory, check unpkg.',
  '  * BLOOM: subtle and tight. The can has a bright accent glow that should bleed a',
  '    little; it must NOT turn the whole image milky. Tune strength, radius and',
  '    threshold conservatively and say what values you chose and why.',
  '  * A CUSTOM GRADE PASS written as a single GLSL fragment shader doing, in order:',
  '      - chromatic aberration that increases toward the frame edges',
  '      - a mild unsharp mask (sharpen) so the can reads as crisp HD',
  '      - film grain, animated by time, very subtle',
  '      - a vignette',
  '      - a gentle contrast S-curve lift in the shadows',
  '    Expose the strengths as uniforms with sane defaults. Use a time uniform driven',
  '    by the dt passed to render().',
  '  * OutputPass last, so tone mapping and colour space stay correct.',
  '  * It must degrade gracefully: if anything fails to import or construct, fall back',
  '    to renderer.render(scene, camera) so the site never goes black. Wrap the setup',
  '    in try/catch and log a single console.warn.',
  '',
  'VERIFY IT YOURSELF: create a throwaway page under ' + ROOT + '/_tmp/ that loads',
  'three 0.169.0 from the same CDN the site uses, imports your module, renders a',
  'trivial scene (a lit sphere) through it into a canvas, and screenshots the result',
  'using the headless-Chrome-over-CDP technique in ' + ROOT + '/_crop.mjs (adapt it).',
  'READ the PNG. Confirm: the image is not black, not blown out, and the sphere is',
  'visibly sharp, bloomed and vignetted. Then delete the throwaway. Report what the',
  'screenshot showed.',
].join('\n')

const API_TASK = [
  'You are verifying a dependency API before other agents rely on it.',
  'Nothing you write ships - your job is to produce a short, accurate reference note.',
  '',
  'TARGET: three.js version 0.169.0, loaded in a browser via an importmap with:',
  '  "three":         "https://unpkg.com/three@0.169.0/build/three.module.js"',
  '  "three/addons/": "https://unpkg.com/three@0.169.0/examples/jsm/"',
  '',
  'Determine, with EVIDENCE - actually fetch the source from unpkg and read it, do not',
  'answer from memory:',
  '  1. The exact import specifiers for: EffectComposer, RenderPass, ShaderPass,',
  '     UnrealBloomPass, OutputPass, SMAAPass, and any others commonly needed.',
  '     Confirm each of those files actually exists at that version - a 404 is a real',
  '     risk. List any that do NOT exist at 0.169.0.',
  '  2. The exact constructor signature and required arguments for each.',
  '  3. Whether EffectComposer needs renderer.outputColorSpace or toneMapping handling',
  '     changed when OutputPass is used, and the correct ordering for',
  '     ACESFilmicToneMapping.',
  '  4. Whether UnrealBloomPass resolution should be a Vector2 of the drawing-buffer',
  '     size, and what setSize expects.',
  '  5. Any breaking change between roughly 0.150 and 0.169 in these classes that',
  '     would bite someone writing this from memory.',
  '',
  'Cross-check at least one claim against a second source - the three.js docs or the',
  'repo examples for that tag - rather than trusting a single fetch.',
  '',
  'Then WRITE your findings to ' + ROOT + '/_api-notes.md as a compact reference: a',
  'table of specifier to constructor signature, the correct composer ordering, and a',
  'short gotchas list. Keep it under 80 lines. Every claim must be one you verified.',
].join('\n')

const SECTIONS_TASK = [
  'YOUR TASK: write TWO new files describing extra page sections, as drop-in',
  'fragments the integrator will wire in. Do NOT edit index.html or style.css.',
  '',
  '  ' + ROOT + '/_sections.html   - markup only, no html/head/body wrapper',
  '  ' + ROOT + '/_sections.css    - styles only',
  '',
  'Write sections that add the density the reference has and the current site lacks:',
  '',
  '  1. A PRODUCT ROW - five cans in a horizontal row, each with a small card below',
  '     it showing a name, a size, a price, and a tiny mono index. On hover the card',
  '     should lift and the accent should bleed in. Look at crop-flavors.png. These',
  '     are NOT the 3D can - they are small flat representations. Build each can as',
  '     pure CSS: a narrow rounded rectangle with a lid, a shard logo drawn as an',
  '     inline SVG, and a per-item --accent. Give each a slightly different accent so',
  '     the row reads as a flavour range.',
  '',
  '  2. A SPLIT SECTION - a greyscale media panel on the left and an enormous italic',
  '     condensed statement on the right, roughly SINCE 2002 PRODUCING in spirit.',
  '     Look at crop-since.png. There are no image assets, so the media panel must be',
  '     a PROCEDURAL CSS composition: layered radial and linear gradients, a noise',
  '     texture, and a subtle animated sheen, that reads as a dark abstract product',
  '     film still rather than a broken image. It must not look like a grey box.',
  '',
  '  3. A DENSE SPEC TABLE - more detailed than the existing .specs grid: a proper',
  '     two-column data table with about 10 rows of mono label and value pairs,',
  '     hairline rules, and small footnote markers. This is the detailed register the',
  '     reference has.',
  '',
  'RULES',
  '  * Reuse the existing design tokens and conventions from css/style.css: the CSS',
  '    custom properties (--accent, --accent-rgb, --bg, --line, --panel, --muted,',
  '    --pad, --font-display, --font-mono), the .mono / .eyebrow / .h2 helpers, the',
  '    data-reveal and data-cursor attributes, and the line plus line__inner reveal',
  '    markup pattern where a heading is involved.',
  '  * Use the SAME comment style as style.css - section banners and WHY comments.',
  '  * Every colour must come from a token so the flavour switcher restyles it.',
  '  * Responsive: these must work down to 390px. Follow the existing breakpoints',
  '    (1024px and 760px).',
  '  * Accessible: real semantics, aria where needed, and honour',
  '    prefers-reduced-motion for the animated sheen.',
  '',
  'VERIFY IT YOURSELF: build a throwaway page under ' + ROOT + '/_tmp/ that inlines',
  'your fragment plus css/style.css and your _sections.css, and screenshot it at',
  '1600x1000 and at 390x844 using the headless-Chrome technique in ' + ROOT + '/_crop.mjs',
  '(adapt it). READ both PNGs. Check nothing overflows, nothing is invisible, the',
  'product row does not wrap badly on mobile, and the media panel does not read as a',
  'flat grey box. Iterate until it looks deliberate. Delete the throwaway. Report',
  'what you saw.',
].join('\n')

phase('Build')

const [label, mesh, postfx, api, sections] = await parallel([
  () => agent(BRIEF + '\n\n' + LABEL_TASK, { label: 'can-label', phase: 'Build', schema: SCHEMA }),
  () => agent(BRIEF + '\n\n' + MESH_TASK, { label: 'can-mesh', phase: 'Build', schema: SCHEMA }),
  () => agent(BRIEF + '\n\n' + POSTFX_TASK, { label: 'postfx', phase: 'Build', schema: SCHEMA }),
  () => agent(API_TASK, { label: 'three-api', phase: 'Build', schema: SCHEMA }),
  () => agent(BRIEF + '\n\n' + SECTIONS_TASK, { label: 'sections', phase: 'Build', schema: SCHEMA }),
])

const built = [label, mesh, postfx, api, sections].filter(Boolean)
log('built ' + built.length + '/5 modules')

phase('Verify')

const CHECKS = [
  { key: 'js/can-label.js', expect: 'makeLabelTexture, LABEL_SERVICE, BAND, refreshLabels', extra: 'label' },
  { key: 'js/can-mesh.js', expect: 'CAN, buildBodyGeometry, buildLid, buildTab, buildRim, buildFoot, buildUnderBase', extra: 'mesh' },
  { key: 'js/postfx.js', expect: 'createPostFX', extra: 'postfx' },
]

const EXTRA = {
  mesh: 'Additionally assert the profile has exactly 84 points, y is monotonic, and bandVBot/bandVTop are exactly 9/83 and 69/83. This is the highest-risk detail in the whole build.',
  label: 'Additionally call makeLabelTexture for a sample flavour and confirm it returns a THREE.CanvasTexture with a non-zero image, then dump it to a PNG you READ and judge against ' + ROOT + '/_ref/crop-can.png. Does it actually look like that - black can, one bold shard logo, vertical wordmark, dense micro-text? Say plainly if it does not.',
  postfx: 'Additionally confirm the try/catch fallback really works - force a construction failure and check the page still renders rather than going black.',
}

const VERDICT_SCHEMA = {
  type: 'object',
  required: ['file', 'passes', 'evidence', 'problems'],
  properties: {
    file: { type: 'string' },
    passes: { type: 'boolean' },
    evidence: { type: 'string', description: 'exact commands run and their output' },
    problems: { type: 'string', description: 'CONFIRMED problems, or the word none' },
  },
}

const verdicts = await parallel(CHECKS.map((c) => () =>
  agent([
    'Adversarially verify a module another agent just wrote. Default to reporting a',
    'problem if you are unsure - a false pass here is expensive.',
    '',
    'FILE: ' + ROOT + '/' + c.key,
    'It is supposed to export: ' + c.expect,
    'Its intended contract is described in its own header comments; read them.',
    '',
    'Do all of this:',
    '  1. Syntax-check it. Run node with --input-type=module --check, piping the file',
    '     in on stdin. Report the exact command and its exact output.',
    '  2. Actually LOAD it in a real browser. Build a throwaway page under ' + ROOT + '/_tmp/',
    '     that imports three from https://unpkg.com/three@0.169.0/build/three.module.js',
    '     and imports the module under test, then reports whether every contracted',
    '     export exists and has the right typeof. Run it through headless Chrome over',
    '     CDP (the technique in ' + ROOT + '/_crop.mjs) and capture console errors and',
    '     exceptions. A module that parses but throws on import is a FAIL.',
    '  3. ' + EXTRA[c.extra],
    '  4. Look for integration hazards: missing exports, wrong argument order, use of',
    '     three APIs that do not exist in 0.169.0, hardcoded sizes, NaN in defaults.',
    '',
    'Report CONFIRMED problems with exact evidence - command plus output - not',
    'suspicions. Clean up your throwaway files.',
  ].join('\n'), { label: 'verify:' + c.key.split('/').pop(), phase: 'Verify', schema: VERDICT_SCHEMA })
))

const ok = verdicts.filter(Boolean)
return {
  built: built.map((b) => ({ file: b.file, summary: b.summary, risks: b.risks })),
  apiNotes: api ? api.summary : null,
  verdicts: ok,
  failed: ok.filter((v) => !v.passes).map((v) => v.file),
}
